version: '3'

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: always
    ports:
      - '4000:3000'
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    container_name: database
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/data/postgres/
    networks:
      - backend

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '8081:80'
    networks:
      - frontend

volumes:
  postgres_data:

networks:
  frontend: {}
  backend: {}